# Generated by Django 6.0 on 2025-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_articles_category_articles_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
